title = "Unity"
version = "2.6.1"
description = "Simple unit testing framework for C. Lightweight, with a single C file and headers, designed for embedded toolchains."
license = "MIT"
canonical_name = "unity"
recipe_url = "https://github.com/ThrowTheSwitch/Unity/archive/refs/tags/v2.6.1.tar.gz"
[dependencies]
