title = "capstone"
version = "5.0.3"
description = "Capstone is a lightweight multi-platform, multi-architecture disassembly framework. It supports ARM, AArch64, x86, M68K, MIPS, PowerPC, SPARC, SystemZ, XCore, and more in a single library."
license = "BSD-3-Clause"
dependencies = "None"
canonical_name = "capstone"
recipe_url = "https://github.com/capstone-engine/capstone/archive/refs/tags/5.0.3.tar.gz"
