title = "libusb"
version = "1.0.27"
description = "libusb is a cross-platform user-space library for USB device communication. It provides synchronous and asynchronous APIs for device discovery and data transfers."
license = "LGPL-2.1"
canonical_name = "libusb"
recipe_url = "https://github.com/libusb/libusb/releases/download/v1.0.27/libusb-1.0.27.tar.bz2"
[dependencies]
udev = ""
