title = "stb"
version = "2024-12-01"
description = "stb is a collection of single-file C libraries by Sean Barrett for image loading, font rendering, audio playback and more. Each library is a single .h or .c file with zero dependencies."
license = "PublicDomain"
dependencies = "None"
canonical_name = "stb"
recipe_url = "https://github.com/nothings/stb/archive/refs/heads/master.tar.gz"
